services:
  frontend:
    build: ./
    container_name: react_frontend
    ports:
      - ${DOCKER_FE_PORT}:${FE_PORT}
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev