# version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: db_postgre_container
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_HOST_PORT}:5432
    volumes:
      - db_postgre_container:/var/lib/postgresql/data
    restart: always

volumes:
  db_postgre_container:
