# Staging environment values
namespace: frontend-staging
replicaCount: 2
image:
  repository: charlilyyyy/tpjazurepythonreactappfe
  tag: "19"
containerPort: 80
ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: staging.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
service:
  type: ClusterIP
  port: 80
# Scheduling - staging prefers control-plane node
nodeSelector:
  kubernetes.io/hostname: minikube
tolerations: []
affinity: {}
