namespace: frontend
replicaCount: 1
image:
  repository: charlilyyyy/tpjazurepythonreactappfe
  tag: "12"
containerPort: 80
ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
service:
  type: ClusterIP
  port: 80
