# Development environment values
namespace: frontend-dev
replicaCount: 1
image:
  repository: charlilyyyy/tpjazurepythonreactappfe
  tag: "dev"  # or "latest" for dev
containerPort: 80
ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: dev.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
service:
  type: ClusterIP
  port: 80
# Scheduling - dev can run on any node
nodeSelector: {}
tolerations: []
affinity: {}
