name: Build and Push Docker Image to Docker Hub 

on:
  push:
    branches:
      - main
    paths:
      - 'fe_react/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.event.head_commit.message != 'skip-ci'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set Docker Image Tag
        run: echo "IMAGE_TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/tpjazurepythonreactappfe:${{ env.IMAGE_TAG }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/tpjazurepythonreactappfe:${{ env.IMAGE_TAG }}

      - name: Optional - Tag as latest
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/tpjazurepythonreactappfe:${{ env.IMAGE_TAG }} ${{ secrets.DOCKERHUB_USERNAME }}/tpjazurepythonreactappfe:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/tpjazurepythonreactappfe:latest
